### ISSUE TITLE
even after configuration of loading image i am getting error

### ISSUE THREAD

**Issue by raghavd17** [maoberlehner/setting-up-a-vue-project-with-webpack-4-and-babel-7#2] opened 2018-07-19 08:15 UTC
I have added the configuration with the following instructions
https://webpack.js.org/guides/asset-management/#loading-images
still, I am getting errors saying file not found.
I have cross checked the file path as well.

![image](https://user-images.githubusercontent.com/1301624/42930156-ddea5af4-8b59-11e8-83eb-68b3b19f359a.png)

**Comment by maoberlehner** [comment] 2018-07-19 08:23
How do you load the image?

**Comment by raghavd17** [comment] 2018-07-19 08:25
I am loading an image inside vue file 

`<a class="navbar-brand" href="#"><img src="../../assets/logo.svg" alt="logo " class="logo" /></a>`

even its not working with png images also.

**Comment by maoberlehner** [comment] 2018-07-19 08:51
Oh, thats a different thing than.

The problem is most likely, that your browser can actually not find your file because it is not placed in the directory which is served by webpack (or the serve:production script).

You have to add and configure the following plugin: https://github.com/webpack-contrib/copy-webpack-plugin

I'm, again, closing this issue. This is not because I wan't to be rude or I don't want to help you, but because this is a webpack configuration thing and **not** a problem with the code in this repository. I don't have the resources to provide support for webpack related issues and this was not inside the scope of my article so I hope you understand my situation.

There are a lot of resources out there explaining how to integrate static files into your webpack build (Google "webpack static assets").

Thanks!

**Closed as completed by maoberlehner** 2018-07-19 08:51 UTC
Labels: question

**Comment by maoberlehner** [comment] 2018-07-19 08:55
I might add, if you're just getting started with webpack and Vue.js I **highly** recommend you to use the Vue CLI: https://cli.vuejs.org/

My article was written before the Vue CLI upgraded to webpack 4 and even then it was intended for people who want to have full control over their build process, for everybody else, the Vue CLI ist highly preferable.
